# ROOT 관리자 생성
CREATE USER admin@localhost identified BY '1111';

# DataBase 생성
CREATE DATABASE OTT;

# Table 삭제
DROP TABLE users;
DROP TABLE UserHistory;
DROP TABLE MemberShip;
DROP TABLE UserMemberShip;
DROP TABLE content;
DROP TABLE review;
DROP TABLE FreeBoard;
DROP TABLE ReviewBoard;
DROP TABLE reviewboardimage;

# Table 생성
SELECT * FROM users;
SELECT * FROM userhistory;
SELECT * FROM membership;
SELECT * FROM content;
SELECT * FROM freeboard;
SELECT * FROM reviewBoard;
SELECT * FROM ReviewBoardImage;

# 회원(Users) 테이블 생성

CREATE TABLE Users(
	UsersId BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	LoginId VARCHAR(12) NOT NULL UNIQUE,
	NickName VARCHAR(10) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	UserPassword VARCHAR(20) NOT NULL,
	Gender ENUM('M', 'F') NOT NULL,
	ProfileFileName VARCHAR(255),
	CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

# 방문기록 (UserHistory) 테이블 생성

CREATE TABLE UserHistory(
	UserHistoryId BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	LoginId VARCHAR(12) NOT NULL,
	UserIP VARCHAR(45) NOT NULL,
	AccessAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UserAgent VARCHAR(255) NOT NULL,
	FOREIGN KEY (LoginId) REFERENCES Users(LoginId) ON DELETE CASCADE);

# 멤버쉽 (MemberShip) 테이블 생성

CREATE TABLE MemberShip(
	MemberShipId BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,        
	UserType ENUM('Free', 'Basic', 'Standard', 'Premium', 'Admin') NOT NULL DEFAULT "Free",
   Price DECIMAL(5, 3) NOT NULL,
   Quality VARCHAR(100),
   MaxDevices INT NOT NULL,
   CanAd BOOLEAN NOT NULL DEFAULT FALSE,
   CanDown BOOLEAN NOT NULL DEFAULT FALSE);
	
# 사용자 멤버쉽 (UserMemberShip) 테이블 생성
	
CREATE TABLE UserMemberShip(
	UserMemberShipId BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	MemberShipId BIGINT UNSIGNED NOT NULL,
	LoginId VARCHAR(12) NOT NULL,
	StartDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	EndDate DATETIME NOT NULL,	
	FOREIGN KEY (MemberShipId) REFERENCES MemberShip(MemberShipId),
	FOREIGN KEY (LoginId) REFERENCES Users(LoginId) ON DELETE CASCADE);

# 콘텐츠(Content) 테이블 생성
	
CREATE TABLE Content(
	ContentId BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Title VARCHAR(255) NOT NULL,
	Info TEXT,
	Genre VARCHAR(100) NOT NULL,
	ReleaseDate VARCHAR(255) NOT NULL,
	Director VARCHAR(100) NOT NULL,
	AgeRating ENUM('ALL', '15', '18', '19') NOT NULL,
	PosterFileName VARCHAR(255) NOT NULL,
	ThumbnailFileName VARCHAR(255) NOT NULL);
	
# 리뷰 (Review) 테이블 생성

CREATE TABLE Review (
	ReviewId	BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ContentId BIGINT UNSIGNED NOT NULL,
   UsersId BIGINT UNSIGNED NOT NULL,
	Content	TEXT	NOT NULL,
	CreatedAt	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	Rating DECIMAL(2, 1)	NOT NULL,
	FOREIGN KEY (ContentId) REFERENCES Content(ContentId) ON DELETE CASCADE,
	FOREIGN KEY (UsersId) REFERENCES	Users(UsersId) ON DELETE CASCADE);
	
# 자유 게시판 (FreeBoard) 테이블 생성

CREATE TABLE FreeBoard (
	FreeBoardId	BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	LoginId VARCHAR(12) NOT NULL,
	Title	VARCHAR(90)	NOT NULL,
	Content	TEXT	NOT NULL,
	Category	ENUM('일반', '질문', '토론', '정보')	NOT NULL	,
	ViewCount INT	NOT NULL	DEFAULT 0,
	CreatedAt DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	IsDeleted Boolean	NOT NULL	DEFAULT FALSE,
	FOREIGN KEY (LoginId) REFERENCES Users(LoginId) ON DELETE CASCADE);

# 자유 게시판 댓글 (FreeBoardComment) 테이블 생성

CREATE TABLE FreeBoardComment (
   CommentId BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   FreeBoardId BIGINT UNSIGNED NOT NULL,
   LoginId VARCHAR(12) NOT NULL,
   Content TEXT NOT NULL,
   Category	ENUM('일반', '질문', '토론', '정보') NOT NULL,
   CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
   FOREIGN KEY (FreeBoardId) REFERENCES FreeBoard(FreeBoardId) ON DELETE CASCADE,
   FOREIGN KEY (LoginId) REFERENCES Users(LoginId) ON DELETE CASCADE);
   
# 리뷰 게시판 (ReviewBoard) 테이블 생성

CREATE TABLE ReviewBoard (
	ReviewBoardId	BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	LoginId	VARCHAR(12) NOT NULL,
	Title	VARCHAR(90)	NOT NULL,
	Content	TEXT	NOT NULL,
	Category	ENUM('영화', '드라마', '애니메이션', '다큐멘터리')	NOT NULL,
	ViewCount	INT	NOT NULL	DEFAULT 0	COMMENT '조회수',
	CreatedAt	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	IsDeleted	Boolean	NOT NULL	DEFAULT FALSE,
	FOREIGN KEY (LoginId) REFERENCES Users(LoginId) ON DELETE CASCADE);
	
# 리뷰 게시판 이미지 (ReviewBoard Image) 테이블 생성

CREATE TABLE ReviewBoardImage (
	ImageId	BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	FileName	VARCHAR(255) NOT NULL,
	ReviewBoardId	BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (ReviewBoardId) REFERENCES ReviewBoard(ReviewBoardId) ON DELETE CASCADE);
	
	
	
	
# 멤버십 테이블 데이터 추가
SELECT * from membership;
INSERT INTO membership(usertype, price, quality, maxdevices, canad, candown) VALUES('Free', 0, NULL, 0, FALSE, FALSE);
INSERT INTO membership(usertype, price, quality, maxdevices, canad, candown) VALUES('Basic', 9.500, 'HD 화질 (720p)', 1, FALSE, FALSE);
INSERT INTO membership(usertype, price, quality, maxdevices, canad, candown) VALUES('Standard', 13.500, 'FULL HD 화질 (1080p)', 2, TRUE, TRUE);
INSERT INTO membership(usertype, price, quality, maxdevices, canad, candown) VALUES('Premium', 17.000, '4K UHD + HDR 화질', 4, TRUE, TRUE);
INSERT INTO membership(usertype, price, quality, maxdevices, canad, candown) VALUES('Admin', 0.0, NULL, 0, FALSE, FALSE);